# docker-compose up [--build]
version: '3'

services:
  app:
    container_name: biblioteca
    build: .
    volumes:
        - .:/go/src/myapp

    # ports:
    #   - 80:8000
    # networks:
    #   - mongo-network
    # environment:
    #   - MONGODB_URI=mongodb://TDTxLE:comemierda1@TDTxLE-mongodb:27017
    #   - DB_USER=TDTxLE
    #   - DB_PWD=comemierda1
    #   - DB_HOST=TDTxLE-mongodb
    #   - DB_POST=27017
    #   - DB_DATABASE=Libreria
    #     # - mysql_root_password_file: /run/secrets/mysql_root_password
    # secrets:
    #     - mysql_root_password

networks:
  mongo-network:
    external: true
      

secrets:
    mysql_root_password:
        file: ./.secret/mysql_root_password.ytext