version: '3'

services:
  app:
    container_name: biblioteca
    build: .
    volumes:
        - .:/go/src/myapp
    ports:
      - 8081:8080

  postgresql:
    image: postgres:16.1-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca

secrets:
    mysql_root_password:
        file: ./.secret/mysql_root_password.ytext


volumes:
  postgresql: